bookmarksRaw = "https://www.codecademy.com/learn/learn-powershell
https://www.codecademy.com/enrolled/courses/learn-ruby
https://www.codecademy.com/learn/learn-go
https://www.codecademy.com/learn/learn-sql
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Debugging_HTML
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Structuring_a_page_of_content
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Mozilla_splash_page
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Basics
https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced
https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Structuring_planet_data
https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Pseudo-classes_and_pseudo-elements
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Combinators
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Handling_different_text_directions
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_media_form_elements
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Styling_tables
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Debugging_CSS
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Organizing
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Fundamental_CSS_comprehension
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Creating_fancy_letterheaded_paper
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/A_cool_looking_box
https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals
https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_lists
https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links
https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts
https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Typesetting_a_homepage
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Introduction
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Normal_Flow
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grid_skills
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Floats
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Multiple-column_Layout
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Media_queries
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Legacy_Layout_Methods
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Supporting_Older_Browsers
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Fundamental_Layout_Comprehension
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Useful_string_methods
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Arrays
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Silly_story_generator
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Functions
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Build_your_own_function
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Return_values
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Image_gallery
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_programming
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Classes_in_JavaScript
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_building_practice
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Adding_bouncing_balls_features
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Implementing_a_promise-based_API
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing_workers
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Sequencing_animations
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Introduction
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Drawing_graphics
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Video_and_audio_APIs
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage
https://developer.mozilla.org/en-US/docs/Learn/Forms/Your_first_form
https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form
https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls
https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types
https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls
https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms
https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling
https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes
https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation
https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data
https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls
https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_forms_through_JavaScript
https://developer.mozilla.org/en-US/docs/Learn/Forms/Property_compatibility_table_for_form_controls
https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility
https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML
https://developer.mozilla.org/en-US/docs/Learn/Accessibility/CSS_and_JavaScript
https://developer.mozilla.org/en-US/docs/Learn/Accessibility/WAI-ARIA_basics
https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Multimedia
https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Mobile
https://developer.mozilla.org/en-US/docs/Learn/Performance/why_web_performance
https://developer.mozilla.org/en-US/docs/Learn/Performance/What_is_web_performance
https://developer.mozilla.org/en-US/docs/Learn/Performance/Perceived_performance
https://developer.mozilla.org/en-US/docs/Learn/Performance/Measuring_performance
https://developer.mozilla.org/en-US/docs/Learn/Performance/Multimedia
https://developer.mozilla.org/en-US/docs/Learn/Performance/video
https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript
https://developer.mozilla.org/en-US/docs/Learn/Performance/HTML
https://developer.mozilla.org/en-US/docs/Learn/Performance/CSS
https://developer.mozilla.org/en-US/docs/Learn/Performance/business_case_for_performance
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Overview
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Deployment
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Introduction
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Main_features
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_first_component
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_rendering_lists
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_methods_events_models
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_styling
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_computed_properties
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_conditional_rendering
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_refs_focus_management
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_resources
https://docs.github.com/en/get-started/quickstart/hello-world
https://docs.github.com/en/get-started/using-git/about-git
https://docs.github.com/en/get-started/quickstart/contributing-to-projects
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Introduction
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Testing_strategies
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/HTML_and_CSS
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/JavaScript
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Accessibility
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Feature_detection
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Automated_testing
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment
https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction
https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Client-Server_overview
https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Web_frameworks
https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Website_security
http://poignant.guide/
https://learning.oreilly.com/course/learn-to-code/9781788834063/
https://learning.oreilly.com/library/view/ruby-in-a/0596002149/
https://learning.oreilly.com/library/view/the-ruby-programming/9780596516178/
https://learning.oreilly.com/library/view/computer-science-programming/9781449356835/
https://learning.oreilly.com/library/view/the-well-grounded-rubyist/9781617295218/
https://learning.oreilly.com/library/view/learning-sql-3rd/9781492057604/
https://learning.oreilly.com/library/view/learn-postgresql/9781837635641/
https://learning.oreilly.com/interactive-lab/postgresql-fundamentals-creating/9781098114336/
https://learning.oreilly.com/course/ruby-on-rails/9780138050351/
https://learning.oreilly.com/library/view/ruby-on-rails/9780138050061/
https://learning.oreilly.com/library/view/agile-web-development/9798888650288/
https://learning.oreilly.com/library/view/modern-front-end-development/9781680509977/
https://learning.oreilly.com/library/view/layered-design-for/9781801813785/
https://medium.com/@sushildamdhere/how-to-document-rest-apis-with-swagger-and-ruby-on-rails-ae4e13177f5d
https://37signals.com/how-we-communicate
https://github.cerner.com/rwcm-norbert/health_benefits_management_server
https://github.cerner.com/rwcm-norbert/benefits_management_engine
https://github.cerner.com/rwcm-norbert/health_benefits_store_engine
https://github.cerner.com/rwcm-norbert/health_benefits_management_engine
https://github.cerner.com/rwcm-norbert/copay_test_price_engine
https://github.cerner.com/rwcm-norbert/qualification_codes_engine
https://github.cerner.com/rwcm-norbert/test_pricing_details_engine
https://github.cerner.com/rwcm-norbert/batch_recalc_engine
https://github.cerner.com/rwcm-norbert/health_benefits_store_server
https://github.cerner.com/HDXTS/hdxts-eligibility-bus-inquiry-gateway-cookbook
https://github.cerner.com/HDXTS/hdxts-eligibility-bus-response-gateway-cookbook
https://github.cerner.com/HDXTS/hdxts-chef-repo
https://github.cerner.com/him-cloud/him_configuration_server
https://github.cerner.com/him-cloud/him_coding_server
https://github.cerner.com/him-cloud/him_coding_engine
https://github.cerner.com/him-cloud/him_chart_completion_server
https://github.cerner.com/him-cloud/organization_search_engine
https://github.cerner.com/him-cloud/personnel_search_engine
https://github.cerner.com/him-cloud/him_chart_completion_engine
https://github.cerner.com/him-cloud/him_configuration_engine
https://github.cerner.com/him-cloud/him_sticky_notes_engine
https://github.cerner.com/him-cloud/him_providers_view_engine
https://github.cerner.com/him-cloud/him_coding_history_engine
https://github.cerner.com/him-cloud/him_letters_engine
https://github.cerner.com/him-cloud/him_chart_analysis_engine
https://github.cerner.com/him-cloud/him_cloud_timers
https://github.cerner.com/him-cloud/document_type_search_engine
https://learning.oreilly.com/course/up-and-running/9781803233147/
https://learning.oreilly.com/library/view/learning-go-2nd/9781098139285/
https://learning.oreilly.com/course/tailwind-css-from/9781804611630/
https://learning.oreilly.com/course/vue-the/9781788992817/
https://learning.oreilly.com/library/view/learning-vue/9781492098812/"

bookmarkCount = 0
bookmarksRaw.each do |i|
    if (i === "h" && i + 1 === "t" && i + 2 === "t" && i + 3 === "p" and i + 4 === "s")
        bookmarkCount++
    end
end
puts bookmarkCount
